"""2025-03-23

Revision ID: 6bcf2ae88049
Revises: 7cc5e13ab80a
Create Date: 2025-03-23 22:56:16.498749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bcf2ae88049'
down_revision: Union[str, None] = '7cc5e13ab80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_api',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('permission_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method', 'path', name='method_path_unique'),
    schema='public'
    )
    op.create_index('idx_permission_ids_gin', 't_api', ['permission_ids'], unique=False, schema='public', postgresql_using='gin')
    op.create_index(op.f('ix_public_t_api_created_by'), 't_api', ['created_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_api_deleted'), 't_api', ['deleted'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_api_method'), 't_api', ['method'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_api_path'), 't_api', ['path'], unique=False, schema='public')
    op.create_table('t_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=256), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'code', name='parent_code_unique'),
    schema='public'
    )
    op.create_index(op.f('ix_public_t_permission_code'), 't_permission', ['code'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_permission_created_by'), 't_permission', ['created_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_permission_deleted'), 't_permission', ['deleted'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_permission_parent_id'), 't_permission', ['parent_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_permission_sort'), 't_permission', ['sort'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_t_permission_sort'), table_name='t_permission', schema='public')
    op.drop_index(op.f('ix_public_t_permission_parent_id'), table_name='t_permission', schema='public')
    op.drop_index(op.f('ix_public_t_permission_deleted'), table_name='t_permission', schema='public')
    op.drop_index(op.f('ix_public_t_permission_created_by'), table_name='t_permission', schema='public')
    op.drop_index(op.f('ix_public_t_permission_code'), table_name='t_permission', schema='public')
    op.drop_table('t_permission', schema='public')
    op.drop_index(op.f('ix_public_t_api_path'), table_name='t_api', schema='public')
    op.drop_index(op.f('ix_public_t_api_method'), table_name='t_api', schema='public')
    op.drop_index(op.f('ix_public_t_api_deleted'), table_name='t_api', schema='public')
    op.drop_index(op.f('ix_public_t_api_created_by'), table_name='t_api', schema='public')
    op.drop_index('idx_permission_ids_gin', table_name='t_api', schema='public', postgresql_using='gin')
    op.drop_table('t_api', schema='public')
    # ### end Alembic commands ###
