"""2025-03-23

Revision ID: 7cc5e13ab80a
Revises: 
Create Date: 2025-03-23 08:34:07.190941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc5e13ab80a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_admin_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('salt', sa.String(length=32), nullable=False),
    sa.Column('ptype', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='public'
    )
    op.create_index(op.f('ix_public_t_admin_user_deleted'), 't_admin_user', ['deleted'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_status'), 't_admin_user', ['status'], unique=False, schema='public')
    op.create_table('t_admin_user_token',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_t_admin_user_token_admin_user_id'), 't_admin_user_token', ['admin_user_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_token_deleted'), 't_admin_user_token', ['deleted'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_token_status'), 't_admin_user_token', ['status'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_t_admin_user_token_status'), table_name='t_admin_user_token', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_token_deleted'), table_name='t_admin_user_token', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_token_admin_user_id'), table_name='t_admin_user_token', schema='public')
    op.drop_table('t_admin_user_token', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_status'), table_name='t_admin_user', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_deleted'), table_name='t_admin_user', schema='public')
    op.drop_table('t_admin_user', schema='public')
    # ### end Alembic commands ###
