"""2025-08-10

Revision ID: 937fa48179af
Revises: e3b6d9297849
Create Date: 2025-08-10 11:11:58.609579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '937fa48179af'
down_revision: Union[str, None] = 'e3b6d9297849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False, comment='文件名称'),
    sa.Column('content_type', sa.String(), nullable=False, comment='文件类型'),
    sa.Column('size', sa.Integer(), nullable=False, comment='文件大小，单位B'),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_t_file_admin_user_id'), 't_file', ['admin_user_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_file_created_at'), 't_file', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_file_deleted'), 't_file', ['deleted'], unique=False, schema='public')
    op.alter_column('t_admin_role', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('t_admin_role', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_admin_role_created_at'), table_name='t_admin_role')
    op.drop_index(op.f('ix_public_admin_role_created_by'), table_name='t_admin_role')
    op.drop_index(op.f('ix_public_admin_role_deleted'), table_name='t_admin_role')
    op.create_index(op.f('ix_public_t_admin_role_created_at'), 't_admin_role', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_role_created_by'), 't_admin_role', ['created_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_role_deleted'), 't_admin_role', ['deleted'], unique=False, schema='public')
    op.alter_column('t_admin_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('t_admin_user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_admin_user_created_at'), table_name='t_admin_user')
    op.drop_index(op.f('ix_public_admin_user_created_by'), table_name='t_admin_user')
    op.drop_index(op.f('ix_public_admin_user_deleted'), table_name='t_admin_user')
    op.drop_index(op.f('ix_public_admin_user_status'), table_name='t_admin_user')
    op.create_index(op.f('ix_public_t_admin_user_created_at'), 't_admin_user', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_created_by'), 't_admin_user', ['created_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_deleted'), 't_admin_user', ['deleted'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_status'), 't_admin_user', ['status'], unique=False, schema='public')
    op.alter_column('t_admin_user_role', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('t_admin_user_role', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_admin_user_role_admin_role_id'), table_name='t_admin_user_role')
    op.drop_index(op.f('ix_public_admin_user_role_admin_user_id'), table_name='t_admin_user_role')
    op.drop_index(op.f('ix_public_admin_user_role_created_at'), table_name='t_admin_user_role')
    op.drop_index(op.f('ix_public_admin_user_role_deleted'), table_name='t_admin_user_role')
    op.create_index(op.f('ix_public_t_admin_user_role_admin_role_id'), 't_admin_user_role', ['admin_role_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_role_admin_user_id'), 't_admin_user_role', ['admin_user_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_role_created_at'), 't_admin_user_role', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_role_deleted'), 't_admin_user_role', ['deleted'], unique=False, schema='public')
    op.alter_column('t_admin_user_token', 'expired_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('t_admin_user_token', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('t_admin_user_token', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_admin_user_token_admin_user_id'), table_name='t_admin_user_token')
    op.drop_index(op.f('ix_public_admin_user_token_created_at'), table_name='t_admin_user_token')
    op.drop_index(op.f('ix_public_admin_user_token_deleted'), table_name='t_admin_user_token')
    op.drop_index(op.f('ix_public_admin_user_token_status'), table_name='t_admin_user_token')
    op.create_index(op.f('ix_public_t_admin_user_token_admin_user_id'), 't_admin_user_token', ['admin_user_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_token_created_at'), 't_admin_user_token', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_token_deleted'), 't_admin_user_token', ['deleted'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_admin_user_token_status'), 't_admin_user_token', ['status'], unique=False, schema='public')
    op.alter_column('t_api', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('t_api', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_api_created_at'), table_name='t_api')
    op.drop_index(op.f('ix_public_api_created_by'), table_name='t_api')
    op.drop_index(op.f('ix_public_api_deleted'), table_name='t_api')
    op.drop_index(op.f('ix_public_api_method'), table_name='t_api')
    op.drop_index(op.f('ix_public_api_path'), table_name='t_api')
    op.create_index(op.f('ix_public_t_api_created_at'), 't_api', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_api_created_by'), 't_api', ['created_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_api_deleted'), 't_api', ['deleted'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_api_method'), 't_api', ['method'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_api_path'), 't_api', ['path'], unique=False, schema='public')
    op.alter_column('t_permission', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('t_permission', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_permission_code'), table_name='t_permission')
    op.drop_index(op.f('ix_public_permission_created_at'), table_name='t_permission')
    op.drop_index(op.f('ix_public_permission_created_by'), table_name='t_permission')
    op.drop_index(op.f('ix_public_permission_deleted'), table_name='t_permission')
    op.drop_index(op.f('ix_public_permission_parent_id'), table_name='t_permission')
    op.drop_index(op.f('ix_public_permission_sort'), table_name='t_permission')
    op.create_index(op.f('ix_public_t_permission_code'), 't_permission', ['code'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_permission_created_at'), 't_permission', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_permission_created_by'), 't_permission', ['created_by'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_permission_deleted'), 't_permission', ['deleted'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_permission_parent_id'), 't_permission', ['parent_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_t_permission_sort'), 't_permission', ['sort'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_t_permission_sort'), table_name='t_permission', schema='public')
    op.drop_index(op.f('ix_public_t_permission_parent_id'), table_name='t_permission', schema='public')
    op.drop_index(op.f('ix_public_t_permission_deleted'), table_name='t_permission', schema='public')
    op.drop_index(op.f('ix_public_t_permission_created_by'), table_name='t_permission', schema='public')
    op.drop_index(op.f('ix_public_t_permission_created_at'), table_name='t_permission', schema='public')
    op.drop_index(op.f('ix_public_t_permission_code'), table_name='t_permission', schema='public')
    op.create_index(op.f('ix_public_permission_sort'), 't_permission', ['sort'], unique=False)
    op.create_index(op.f('ix_public_permission_parent_id'), 't_permission', ['parent_id'], unique=False)
    op.create_index(op.f('ix_public_permission_deleted'), 't_permission', ['deleted'], unique=False)
    op.create_index(op.f('ix_public_permission_created_by'), 't_permission', ['created_by'], unique=False)
    op.create_index(op.f('ix_public_permission_created_at'), 't_permission', ['created_at'], unique=False)
    op.create_index(op.f('ix_public_permission_code'), 't_permission', ['code'], unique=False)
    op.alter_column('t_permission', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('t_permission', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_t_api_path'), table_name='t_api', schema='public')
    op.drop_index(op.f('ix_public_t_api_method'), table_name='t_api', schema='public')
    op.drop_index(op.f('ix_public_t_api_deleted'), table_name='t_api', schema='public')
    op.drop_index(op.f('ix_public_t_api_created_by'), table_name='t_api', schema='public')
    op.drop_index(op.f('ix_public_t_api_created_at'), table_name='t_api', schema='public')
    op.create_index(op.f('ix_public_api_path'), 't_api', ['path'], unique=False)
    op.create_index(op.f('ix_public_api_method'), 't_api', ['method'], unique=False)
    op.create_index(op.f('ix_public_api_deleted'), 't_api', ['deleted'], unique=False)
    op.create_index(op.f('ix_public_api_created_by'), 't_api', ['created_by'], unique=False)
    op.create_index(op.f('ix_public_api_created_at'), 't_api', ['created_at'], unique=False)
    op.alter_column('t_api', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('t_api', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_t_admin_user_token_status'), table_name='t_admin_user_token', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_token_deleted'), table_name='t_admin_user_token', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_token_created_at'), table_name='t_admin_user_token', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_token_admin_user_id'), table_name='t_admin_user_token', schema='public')
    op.create_index(op.f('ix_public_admin_user_token_status'), 't_admin_user_token', ['status'], unique=False)
    op.create_index(op.f('ix_public_admin_user_token_deleted'), 't_admin_user_token', ['deleted'], unique=False)
    op.create_index(op.f('ix_public_admin_user_token_created_at'), 't_admin_user_token', ['created_at'], unique=False)
    op.create_index(op.f('ix_public_admin_user_token_admin_user_id'), 't_admin_user_token', ['admin_user_id'], unique=False)
    op.alter_column('t_admin_user_token', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('t_admin_user_token', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('t_admin_user_token', 'expired_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_t_admin_user_role_deleted'), table_name='t_admin_user_role', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_role_created_at'), table_name='t_admin_user_role', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_role_admin_user_id'), table_name='t_admin_user_role', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_role_admin_role_id'), table_name='t_admin_user_role', schema='public')
    op.create_index(op.f('ix_public_admin_user_role_deleted'), 't_admin_user_role', ['deleted'], unique=False)
    op.create_index(op.f('ix_public_admin_user_role_created_at'), 't_admin_user_role', ['created_at'], unique=False)
    op.create_index(op.f('ix_public_admin_user_role_admin_user_id'), 't_admin_user_role', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_public_admin_user_role_admin_role_id'), 't_admin_user_role', ['admin_role_id'], unique=False)
    op.alter_column('t_admin_user_role', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('t_admin_user_role', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_t_admin_user_status'), table_name='t_admin_user', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_deleted'), table_name='t_admin_user', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_created_by'), table_name='t_admin_user', schema='public')
    op.drop_index(op.f('ix_public_t_admin_user_created_at'), table_name='t_admin_user', schema='public')
    op.create_index(op.f('ix_public_admin_user_status'), 't_admin_user', ['status'], unique=False)
    op.create_index(op.f('ix_public_admin_user_deleted'), 't_admin_user', ['deleted'], unique=False)
    op.create_index(op.f('ix_public_admin_user_created_by'), 't_admin_user', ['created_by'], unique=False)
    op.create_index(op.f('ix_public_admin_user_created_at'), 't_admin_user', ['created_at'], unique=False)
    op.alter_column('t_admin_user', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('t_admin_user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_t_admin_role_deleted'), table_name='t_admin_role', schema='public')
    op.drop_index(op.f('ix_public_t_admin_role_created_by'), table_name='t_admin_role', schema='public')
    op.drop_index(op.f('ix_public_t_admin_role_created_at'), table_name='t_admin_role', schema='public')
    op.create_index(op.f('ix_public_admin_role_deleted'), 't_admin_role', ['deleted'], unique=False)
    op.create_index(op.f('ix_public_admin_role_created_by'), 't_admin_role', ['created_by'], unique=False)
    op.create_index(op.f('ix_public_admin_role_created_at'), 't_admin_role', ['created_at'], unique=False)
    op.alter_column('t_admin_role', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('t_admin_role', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_public_t_file_deleted'), table_name='t_file', schema='public')
    op.drop_index(op.f('ix_public_t_file_created_at'), table_name='t_file', schema='public')
    op.drop_index(op.f('ix_public_t_file_admin_user_id'), table_name='t_file', schema='public')
    op.drop_table('t_file', schema='public')
    # ### end Alembic commands ###
