"""2025-03-25

Revision ID: 965597c9e5ae
Revises: 6bcf2ae88049
Create Date: 2025-03-25 21:41:52.656620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965597c9e5ae'
down_revision: Union[str, None] = '6bcf2ae88049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_admin_user', sa.Column('created_by', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_public_t_admin_user_created_by'), 't_admin_user', ['created_by'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_t_admin_user_created_by'), table_name='t_admin_user', schema='public')
    op.drop_column('t_admin_user', 'created_by')
    # ### end Alembic commands ###
