"""2025-03-25

Revision ID: ac8efa82ea98
Revises: 965597c9e5ae
Create Date: 2025-03-25 22:03:33.705764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8efa82ea98'
down_revision: Union[str, None] = '965597c9e5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_name_trgm', 't_admin_user', ['name'], unique=False, schema='public', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_username_trgm', 't_admin_user', ['username'], unique=False, schema='public', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_username_trgm', table_name='t_admin_user', schema='public', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.drop_index('idx_name_trgm', table_name='t_admin_user', schema='public', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
